import { EntityTypeEnum, IActor } from '../common'
import { MissType, ParamsNameEnum, PrefabPathEnum, SkillPathEnum, Special, TexturePathEnum } from '../enum'

const actors: { [key: string]: IActor } = {
  soldier: {
    actorName: '战士',
    prompt: [],
    // 之后改为只存技能序号
    skills: {
      // 这里应该只持有技能编号比较好
      0: [
        {
          name: '砍',
          type: [1],
          desc: '贫弱的攻击',
          damage: 1,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Kan,
          animal: ParamsNameEnum.Kan, //默认和particle一致
        },
        {
          name: '跳',
          type: [3],
          desc: '躲避射击',
          particle: SkillPathEnum.Jump,
          missType: MissType.Bullet,
        },
        {
          name: '挡',
          type: [2],
          desc: '举盾防御',
          defense: 2,
          particle: SkillPathEnum.Dang,
          shield: SkillPathEnum.RoundShieldFrame,
        },
        {
          name: '蓄',
          type: [0],
          desc: '获得一点能量',
          power: 1,
          target: 1,
          particle: SkillPathEnum.Xu,
        },
      ],
      1: [
        {
          name: '爱心盾',
          type: [1, 2],
          desc: '治疗并防御',
          damage: -1,
          defense: 3,
          target: 1,
          speed: 1,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.HeartShield,
          shield: SkillPathEnum.HeartShieldFrame,
        },
        {
          name: '挖地',
          type: [3],
          desc: '临时避难所，躲避几乎所有攻击',
          location: 2,
          particle: SkillPathEnum.Spade,
        },
        {
          name: '十字弩',
          type: [1],
          desc: '远程射击',
          damage: 2,
          speed: 1,
          range: ['0', '1'],
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.Crossbow,
          bullet: EntityTypeEnum.Crossbow,
        },
        {
          name: '反射盾',
          type: [2, 5],
          special: Special.Reflect,
          desc: '防御并反弹远程弹丸攻击',
          defense: 3,
          particle: SkillPathEnum.ShieldReflect,
          shield: SkillPathEnum.ShieldReflectFrame,
        },
      ],
      2: [
        {
          name: '尖刺盾',
          type: [2, 4, 5],
          special: Special.Reflect,
          desc: '你的防御更加严密并且将对近战攻击造成1反伤',
          damage: 1,
          defense: 1,
          target: 0,
          particle: SkillPathEnum.SpikedShield,
          shield: SkillPathEnum.SpikedShieldFrame,
        },
        {
          name: '蓄力一击',
          type: [1],
          desc: '快准狠的一击，对盾牌造成额外两点伤害',
          damage: 2,
          broken: 2,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.ShieldImpact,
        },
        {
          name: '举盾攻击',
          type: [1, 2],
          desc: '防御的同时发起进攻',
          damage: 2,
          defense: 2,
          target: 0,
          speed: 0,
          particle: SkillPathEnum.Spartan,
        },
        {
          name: '盾墙',
          type: [4],
          desc: '你将保持防御',
          particle: SkillPathEnum.ShieldEchoes,
        },
      ],
      3: [
        {
          name: '城墙',
          type: [3, 4, 5],
          desc: '筑起城墙，坚守不退！(将十字弩替换为火油十字弩，无法使用闪避和近战能力，但受到的远程伤害-1，同时视为在空中)',
          location: 1,
          particle: SkillPathEnum.CrenulatedShield,
        },
        {
          name: '陷阱',
          type: [0, 4, 5],
          desc: '假装蓄力，其实放下陷阱。(陷阱将持续存在直到阻拦对方近战攻击)',
          power: 0,
          damage: 2,
          particle: SkillPathEnum.FloorHatch,
        },
        {
          name: '嗜血狂暴',
          type: [4, 5],
          desc: '你的攻击伤害+1，并且近战会恢复你的生命，但是未命中会降低生命',
          damage: 1,
          particle: SkillPathEnum.Enrage,
        },
        {
          name: '无限剑制',
          type: [4],
          desc: '每回合发出一次快速飞剑攻击',
          damage: 1,
          particle: SkillPathEnum.SwordTie,
        },
      ],
      4: [
        {
          name: '石中剑',
          type: [1],
          desc: 'ex-咖喱棒！',
          damage: 5,
          speed: 0,
          range: ['01'],
          longrang: true,
          particle: SkillPathEnum.AncientSword,
        },
        {
          name: '火星撞地球',
          type: [5],
          desc: '听说恐龙也是这么灭绝的，对敌我双方造成当前生命值伤害',
          particle: SkillPathEnum.UnstableProjectile,
        },
        {
          name: '冲锋',
          type: [1, 2],
          range: ['0'],
          desc: '带盾撞人，获得防御量的伤害加成',
          damage: 2,
          defense: 2,
          particle: SkillPathEnum.ShieldBash,
        },
      ],
    },
  },
  animeMan: {
    actorName: '动漫人',
    prompt: [],
    skills: {
      // 这里应该只持有技能编号比较好
      0: [
        {
          name: '砍',
          type: [1],
          desc: '贫弱的攻击',
          damage: 1,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Kan,
          animal: ParamsNameEnum.Kan, //默认和particle一致
        },
        {
          name: '跳',
          type: [3],
          desc: '躲避射击',
          particle: SkillPathEnum.Jump,
          missType: MissType.Bullet,
        },

        {
          name: '挡',
          type: [2],
          desc: '举盾防御',
          defense: 2,
          particle: SkillPathEnum.Dang,
          shield: SkillPathEnum.RoundShieldFrame,
        },
        {
          name: '蓄',
          type: [0],
          desc: '获得一点能量',
          power: 1,
          target: 1,
          particle: SkillPathEnum.Xu,
        },
      ],
      1: [
        {
          name: '遁',
          type: [3, 5],
          desc: '躲避单范围攻击',
          particle: SkillPathEnum.Wood,
        },
        {
          name: '舞空术',
          type: [3],
          desc: '躲避慢速单范围攻击，同时发起一次空中近身攻击',
          particle: SkillPathEnum.Dodging,
        },
        {
          name: '跟踪波',
          type: [2, 5],
          desc: '防御并反弹远程弹丸攻击',
          defense: 3,
          particle: SkillPathEnum.gengzongbo,
        },
        {
          name: '波',
          type: [1, 2],
          desc: '治疗并防御',
          damage: -1,
          defense: 3,
          target: 1,
          speed: 1,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.bo,
        },
      ],
      2: [
        {
          name: '',
          type: [2, 4, 5],
          special: Special.Reflect,
          desc: '召唤两个分身，重复动作，受到伤害会消失，将砍替换为螺旋丸',
          damage: 1,
          defense: 1,
          target: 0,
          particle: SkillPathEnum.SpikedShield,
          shield: SkillPathEnum.SpikedShieldFrame,
        },
        {
          name: '写轮眼',
          type: [1],
          desc: '复制对手当前行动',
          damage: 2,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.xielunyan,
        },
        {
          name: '天照',
          type: [1, 2],
          desc: '无视防御，下回合额外造成一点伤害',
          damage: 1,
          defense: 2,
          target: 0,
          speed: 0,
          particle: SkillPathEnum.tianzhao,
        },
        {
          name: '龟波气功',
          type: [4],
          desc: '',
          damage: 3,
          particle: SkillPathEnum.qigong,
        },
      ],
      3: [
        {
          name: '界王拳',
          type: [3, 4, 5],
          desc: '近战造成四倍伤害',
          location: 1,
          particle: SkillPathEnum.jiewangquan,
        },
        {
          name: '三重罗生门',
          type: [0, 4, 5],
          desc: '每重都有两点防御力',
          power: 0,
          damage: 2,
          particle: SkillPathEnum.luoshengmen,
        },
        {
          name: '龟波气功',
          type: [4],
          desc: '',
          damage: 5,
          particle: SkillPathEnum.qigong,
        },
        {
          name: '影分身',
          type: [2, 4, 5],
          special: Special.Reflect,
          desc: '召唤两个分身，重复自身动作，抵挡一点伤害后消失，将砍替换为螺旋丸',
          damage: 1,
          defense: 1,
          target: 0,
          particle: SkillPathEnum.RelationshipBounds,
        },
      ],
      4: [
        {
          name: '元气弹',
          type: [1],
          desc: 'ex-咖喱棒！',
          damage: 4,
          speed: 0,
          range: ['012'],
          longrang: true,
          particle: SkillPathEnum.yuanqidan,
        },
        {
          name: '赛亚人变身',
          type: [5],
          desc: '保留两格气，波类技能升级',
          particle: SkillPathEnum.aura,
        },
        {
          name: '尾兽玉',
          type: [1, 2],
          range: ['0'],
          desc: '快速远距离单体攻击',
          damage: 6,
          defense: 2,
          particle: SkillPathEnum.weishou,
        },
      ],
    },
  },
  joker: {
    actorName: '小丑',
    prompt: [],
    skills: {
      // 这里应该只持有技能编号比较好
      0: [
        {},
        {
          name: '蓄',
          type: [0],
          desc: '获得一点能量',
          power: 1,
          target: 1,
          particle: SkillPathEnum.Xu,
        },

        {},
        {},
      ],
      1: [
        {},
        {
          name: '血祭',
          type: [3],
          desc: '一血换三气，易伤，受到攻击受到额外一点伤害',
          particle: SkillPathEnum.Dodging,
        },
        {},
        {},
      ],
      2: [
        {},
        {
          name: '小丑喇叭',
          type: [1],
          desc: '偏斜所有攻击',
          damage: 2,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.xielunyan,
        },
        {},
        {},
      ],
      3: [
        {},
        {
          name: '射击',
          type: [0, 4, 5],
          desc: '每重都有两点防御力',
          power: 0,
          damage: 4,
          particle: SkillPathEnum.luoshengmen,
        },
        {},
        {},
      ],
      4: [
        {},
        {
          name: '狂欢夜',
          type: [5],
          desc: '小丑喇叭不消耗气',
          particle: SkillPathEnum.aura,
        },
        {},
      ],
    },
  },
}

export default actors
