import { EntityTypeEnum, IActor } from '../common'
import { ParamsNameEnum, PrefabPathEnum, SkillPathEnum, TexturePathEnum } from '../enum'

const actors: { [key: string]: IActor } = {
  soldier: {
    actorName: '战士',
    prompt: [],
    skills: {
      // 这里应该只持有技能编号比较好
      0: [
        {
          name: '砍',
          type: [1],
          desc: '贫弱的攻击',
          damage: 1,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Kan,
          animal: ParamsNameEnum.Kan, //默认和particle一致
        },
        {
          name: '跳',
          type: [3],
          desc: '躲避射击',
          particle: SkillPathEnum.Jump,
        },
        {
          name: '挡',
          type: [2],
          desc: '举盾防御',
          defense: 2,
          particle: SkillPathEnum.Dang,
          shield: SkillPathEnum.RoundShieldFrame,
        },
        {
          name: '蓄',
          type: [0],
          desc: '获得一点能量',
          power: 1,
          target: 1,
          particle: SkillPathEnum.Xu,
        },
      ],
      1: [
        {
          name: '爱心盾',
          type: [1, 2],
          desc: '治疗并防御',
          damage: -1,
          defense: 3,
          target: 1,
          speed: 1,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.HeartShield,
        },
        {
          name: '挖地',
          type: [3],
          desc: '临时避难所，躲避几乎所有攻击',
          location: 2,
          particle: SkillPathEnum.Spade,
        },
        {
          name: '十字弩',
          type: [1],
          desc: '远程射击',
          damage: 2,
          speed: 1,
          range: ['0', '1'],
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.Crossbow,
          bullet: EntityTypeEnum.Crossbow, //bullet存在就代表是远程弹丸攻击
        },
        {
          name: '反射盾',
          type: [2, 5],
          desc: '防御并反弹远程弹丸攻击',
          defense: 3,
          particle: SkillPathEnum.ShieldReflect,
        },
      ],
      2: [
        {
          name: '尖刺盾',
          type: [2, 4, 5],
          desc: '你的防御更加严密并且将对近战攻击造成1反伤',
          damage: 1,
          defense: 1,
          target: 0,
          particle: SkillPathEnum.SpikedShield,
        },
        {
          name: '蓄力一击',
          type: [1],
          desc: '快准狠的一击，无视对方防御',
          damage: 2,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.ShieldImpact,
        },
        {
          name: '举盾攻击',
          type: [1, 2],
          desc: '防御的同时发起进攻',
          damage: 2,
          defense: 2,
          target: 0,
          speed: 0,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Spartan,
        },
        {
          name: '盾墙',
          type: [4],
          desc: '你将保持防御',
          particle: SkillPathEnum.ShieldEchoes,
        },
      ],
      3: [
        {
          name: '城墙',
          type: [3, 4, 5],
          desc: '筑起城墙，坚守不退！(将砍替换为十字弩，无法跳跃，但受到的远程伤害-1，同时视为在空中)',
          location: 1,
          particle: SkillPathEnum.CrenulatedShield,
        },
        {
          name: '陷阱',
          type: [0, 4, 5],
          desc: '假装蓄力，其实放下陷阱。(陷阱将持续存在直到阻拦对方近战攻击)',
          power: 0,
          damage: 2,
          particle: SkillPathEnum.FloorHatch,
        },
        {
          name: '嗜血狂暴',
          type: [4, 5],
          desc: '你的攻击伤害+1，并且近战会恢复你的生命，但是未命中会降低生命',
          damage: 1,
          particle: SkillPathEnum.Enrage,
        },
        {
          name: '无限剑制',
          type: [4],
          desc: '每回合发出一次快速飞剑攻击',
          damage: 1,
          particle: SkillPathEnum.SwordTie,
        },
      ],
      4: [
        {
          name: '石中剑',
          type: [1],
          desc: 'ex-咖喱棒！',
          damage: 5,
          speed: 0,
          range: ['01'],
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.AncientSword,
        },
        {
          name: '火星撞地球',
          type: [5],
          desc: '听说恐龙也是这么灭绝的，对敌我双方造成致命伤害',
          particle: SkillPathEnum.UnstableProjectile,
        },
        {
          name: '冲锋',
          type: [1, 2],
          desc: '带盾撞人，获得防御量的伤害加成',
          damage: 2,
          defense: 2,
          particle: SkillPathEnum.ShieldBash,
        },
      ],
    },
  },
  animeMan: {
    actorName: '动漫人',
    prompt: [],
    skills: {
      // 这里应该只持有技能编号比较好
      0: [
        {
          name: '砍',
          type: [1],
          desc: '贫弱的攻击',
          damage: 1,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Kan,
          animal: ParamsNameEnum.Kan, //默认和particle一致
        },
        {
          name: '舞空术',
          type: [3],
          desc: '躲避近战',
          particle: SkillPathEnum.Jump,
        },
        {
          name: '挡',
          type: [2],
          desc: '举盾防御',
          defense: 2,
          particle: SkillPathEnum.Dang,
          shield: SkillPathEnum.RoundShieldFrame,
        },
        {
          name: '蓄',
          type: [0],
          desc: '获得一点能量',
          power: 1,
          target: 1,
          particle: SkillPathEnum.Xu,
        },
      ],
      1: [
        {
          name: '波',
          type: [1, 2],
          desc: '治疗并防御',
          damage: -1,
          defense: 3,
          target: 1,
          speed: 1,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.HeartShield,
        },
        {
          name: '遁',
          type: [3, 5],
          desc: '躲避单范围攻击',
          particle: SkillPathEnum.Spade,
        },
        {
          name: '十字弩',
          type: [2],
          desc: '远程射击',
          damage: 2,
          speed: 1,
          range: ['0','1'],
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.Crossbow,
        },
        {
          name: '反射盾',
          type: [2, 5],
          desc: '防御并反弹远程弹丸攻击',
          defense: 3,
          particle: SkillPathEnum.ShieldReflect,
        },
      ],
      2: [
        {
          name: '跟踪波',
          type: [2, 4, 5],
          desc: '你的防御更加严密并且将对近战攻击造成1反伤',
          damage: 1,
          defense: 1,
          target: 0,
          particle: SkillPathEnum.SpikedShield,
        },
        {
          name: '蓄力一击',
          type: [1],
          desc: '快准狠的一击，无视对方防御',
          damage: 2,
          speed: 0,
          target: 0,
          range: ['0'],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.ShieldImpact,
        },
        {
          name: '举盾攻击',
          type: [1, 2],
          desc: '防御的同时发起进攻',
          damage: 2,
          defense: 2,
          target: 0,
          speed: 0,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.Spartan,
        },
        {
          name: '盾墙',
          type: [4],
          desc: '你将保持防御',
          particle: SkillPathEnum.ShieldEchoes,
        },
      ],
      3: [
        {
          name: '龟波气功',
          type: [3, 4, 5],
          desc: '筑起城墙，坚守不退！(将砍替换为十字弩，无法跳跃，但受到的远程伤害-1，同时视为在空中)',
          location: 1,
          particle: SkillPathEnum.CrenulatedShield,
        },
        {
          name: '陷阱',
          type: [0, 4, 5],
          desc: '假装蓄力，其实放下陷阱。(陷阱将持续存在直到阻拦对方近战攻击)',
          power: 0,
          damage: 2,
          particle: SkillPathEnum.FloorHatch,
        },
        {
          name: '嗜血狂暴',
          type: [4, 5],
          desc: '你的攻击伤害+1，并且近战会恢复你的生命，但是未命中会降低生命',
          damage: 1,
          particle: SkillPathEnum.Enrage,
        },
        {
          name: '无限剑制',
          type: [4],
          desc: '每回合发出一次快速飞剑攻击',
          damage: 1,
          particle: SkillPathEnum.SwordTie,
        },
      ],
      4: [
        {
          name: '元气弹',
          type: [1],
          desc: 'ex-咖喱棒！',
          damage: 5,
          speed: 0,
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.AncientSword,
        },
        {
          name: '火星撞地球',
          type: [5],
          desc: '听说恐龙也是这么灭绝的，对敌我双方造成致命伤害',
          particle: SkillPathEnum.UnstableProjectile,
        },
        {
          name: '冲锋',
          type: [1, 2],
          desc: '带盾撞人，获得防御量的伤害加成',
          damage: 2,
          defense: 2,
          particle: SkillPathEnum.ShieldBash,
        },
      ],
    },
  },
}

export default actors
