import { IActor } from '../common'
import { SkillPathEnum } from '../enum'

const actors: { [key: string]: IActor } = {
  soldier: {
    actorName: '战士',
    prompt: [],
    skills: {
      0: [
        {
          name: '砍',
          type: [1],
          desc: '贫弱的攻击',
          damage: 1,
          speed: 0,
          target: 0,
          range: [0],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.kan,
        },
        {
          name: '跳',
          type: [3],
          desc: '躲避射击',
          location: 1,
          particle: SkillPathEnum.jump,
        },
        {
          name: '挡',
          type: [2],
          desc: '贫弱的攻击',
          defense: 2,
          particle: SkillPathEnum.dang,
        },
        {
          name: '蓄',
          type: [0],
          desc: '蓄积能量',
          power: 1,
          particle: SkillPathEnum.xu,
        },
      ],
      1: [
        {
          name: '爱心盾',
          type: [1, 2],
          desc: '治疗并防御',
          damage: -1,
          defense: 2,
          target: 1,
          speed: 1,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.heartShield,
        },
        {
          name: '挖地',
          type: [3],
          desc: '临时避难所，',
          location: 2,
          particle: SkillPathEnum.spade,
        },
        {
          name: '十字弩',
          type: [2],
          desc: '远程射击',
          damage: 2,
          target: 0,
          speed: 1,
          range: [0, 1],
          longrang: true,
          pierce: false,
          particle: SkillPathEnum.crossbow,
        },
        {
          name: '反射盾',
          type: [2, 5],
          desc: '防御并反弹远程射击',
          defense: 2,
          particle: SkillPathEnum.shieldReflect,
        },
      ],
      2: [
        {
          name: '尖刺盾',
          type: [2, 4],
          desc: '持续效果，你的防御对近战攻击造成反伤',
          damage: 1,
          target: 0,
          particle: SkillPathEnum.spikedShield,
        },
        {
          name: '蓄力一击',
          type: [1],
          desc: '快准狠，无视对方防御',
          damage: 2,
          speed: 0,
          target: 0,
          range: [0],
          longrang: false,
          pierce: true,
          particle: SkillPathEnum.shieldImpact,
        },
        {
          name: '举盾攻击',
          type: [1, 2],
          desc: '防御的同时发起进攻',
          damage: 2,
          defense: 2,
          target: 0,
          speed: 0,
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.spartan,
        },
        {
          name: '盾墙',
          type: [4],
          desc: '你将保持防御',
          particle: SkillPathEnum.shieldEchoes,
        },
      ],
      3: [
        {
          name: '城墙',
          type: [3, 4, 5],
          desc: '筑起城墙，坚守不退！将砍替换为十字弩，无法跳跃，但受到的远程伤害-1，同时视为在空中',
          location: 1,
          particle: SkillPathEnum.crenulatedShield,
        },
        {
          name: '陷阱',
          type: [0, 4, 5],
          desc: '假装蓄力，其实放下陷阱。陷阱将持续存在直到阻拦对方近战攻击',
          power: 0,
          damage: 2,
          particle: SkillPathEnum.floorHatch,
        },
        {
          name: '嗜血狂暴',
          type: [4, 5],
          desc: '你的近战攻击伤害+1，并且会恢复你的生命，但是未命中会降低生命',
          damage: 1,
          defense: 2,
          particle: SkillPathEnum.enrage,
        },
        {
          name: '无限剑制',
          type: [4],
          desc: '每回合发出一次快速飞剑攻击',
          damage: 1,
          particle: SkillPathEnum.swordTie,
        },
      ],
      4: [
        {
          name: '石中剑',
          type: [1],
          desc: 'ex-咖喱棒！',
          damage: 5,
          speed: 0,
          range: [0, 1],
          longrang: false,
          pierce: false,
          particle: SkillPathEnum.ancientSword,
        },
        {
          name: '火星撞地球',
          type: [5],
          desc: '听说恐龙也是这么灭绝的，对敌我双方造成致命伤害',
          particle: SkillPathEnum.unstableProjectile,
        },
        {
          name: '冲锋',
          type: [1, 2],
          desc: '带盾撞人，获得防御量的伤害加成',
          damage: 2,
          defense: 2,
          particle: SkillPathEnum.shieldBash,
        },
      ],
    },
  },
}

export default actors
